### ISSUE TITLE
BE: Detailed Card

### ISSUE THREAD

**Issue by moffatethan** [hatchways/team-water-polo#2]
tags, deadline, attachments, only show up when you add. No comments

**Comment by VAggrippino** [comment]
@moffatethan  There's really not enough information for me to make any progress on this task.
I'm guessing that we need the database backend for the cards.

Here's my guess for what is needed for this task:
### Create the data model to be used for the individual Kanban cards
- Each card object will need to have at least the following properties:
    - tags: Array
    - color code: String
    - deadline: Date
    - attachments: Array of objects? (needs further discussion)

I don't have any idea what the following means:

> only show up when you add. No comments

**Comment by VAggrippino** [comment]
@moffatethan There's still not enough information for me to do anything with this.
Your comment was based on my incorrect guess about this card's purpose.
During our recent meeting, you said that this was an Express routes task.
During a previous meeting, you showed me some UI/UX things regarding which sections should show in the card's UI.

**Comment by moffatethan** [comment]
Your task is to create a route that gets a card from the database and this may require some changes to the card schema such as adding `description`, `deadline`, etc. Please look at the tickets properties and add those into the card where  necessary. 

In `routes/card.js` there is the routes for the card, create a new route that gets the card id as a parameter. Then in the `controllers/card.js` you want to make a controller that handles that route and fetches the card information.

This is as much information I can give you, if you still need clarification then please let me know.

Thanks!
